# Uncomment the next line to define a global platform for your project
 platform :ios, '10.0'

target 'BKSXStudaySwiftProject' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for BKSXStudaySwiftProject
  pod 'Moya', '~> 14.0.0-alpha.1'
  pod 'Reachability', '~> 3.2'
  pod 'SwiftyJSON', '~> 5.0.0'
  pod 'HandyJSON', '~> 5.0.0'
  pod 'Charts', '~> 3.3.0'
  pod 'SnapKit', '~> 5.0.0'
  pod 'IQKeyboardManagerSwift', '~> 6.3.0'
  pod 'Dollar', '~> 8.0.0'
  pod 'ObjectMapper', '~> 3.4.2'
  pod 'SVProgressHUD', '~> 2.2.5'
  pod 'BMPlayer', '~> 1.3.0'
  target 'BKSXStudaySwiftProjectTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'BKSXStudaySwiftProjectUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
