# Uncomment the next line to define a global platform for your project
 platform :ios, '10.0'

target 'BKSXStudaySwiftProject' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for BKSXStudaySwiftProject
  pod 'Moya', '~> 11.0.2'
  pod 'Reachability', '~> 3.2'
  pod 'SwiftyJSON', '~> 4.1.0'
  pod 'HandyJSON', '~> 4.1.1'
  pod 'Charts', '~> 3.1.1'
  pod 'SnapKit', '~> 4.0.0'
  pod 'IQKeyboardManagerSwift', '~> 6.0.2'
  target 'BKSXStudaySwiftProjectTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'BKSXStudaySwiftProjectUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
